updates python to v3.11
sandiego-rh/8Knot pull request #209
Opened 2022-10-24 22:51 UTC by JamesKunstle

newer python is very fast relative to 3.10.

we're fast-forwarding our versions to python's most up-to-date version to get those speed increases.

Signed-off-by: James Kunstle <jkunstle@bu.edu>

2022-10-25 14:32 UTC, cdolfi requested changes
Github actions is giving a warning for not specifying version type. For dependency reasons I think it would be goo to manually give 3.11 and us continue to update it as new python versions come out

2022-10-25 15:46 UTC, JamesKunstle commented
@cdolfi okay that's fine, do you mean to say 3.11 or 3.10?

2022-10-25 21:15 UTC, JamesKunstle commented
@cdolfi 3.11 isn't stable w/ Pipenv so let's merge 3.10 and work on 3.11 later when it's more mature.

2022-10-26 14:52 UTC, cdolfi approved these changes

2022-10-26 14:54 UTC, merged